Account/urls.py
from django.urls import path
from .views import *

app_name = 'account'

urlpatterns = [
    path('register/', register_request, name='register'),
    path('login/', login_request, name='login'),
    path('logout/', logout_request, name='logout'),
]

Product/urls.py
from django.urls import path
from .views import index, products, category_detail, product_detail

app_name = 'product'

urlpatterns = [
    path('', index, name='home'),
    path('products/', products, name='products'),
    path('category/<slug:slug>/', category_detail, name='category_detail'),
    path('product/<slug:slug>/', product_detail, name='product_detail'),
]

Project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Product.urls')),
    path('account/', include('Account.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Account/models.py
from django.db import models

# Create your models here.

Product/models.py
from django.db import models
from django.utils.text import slugify
from ckeditor.fields import RichTextField

# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=300)
    slug = models.SlugField(unique=True, blank=True, null=False, db_index=True, editable=False)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)

class Product(models.Model):
    name = models.CharField(max_length=300)
    price = models.IntegerField()
    description = RichTextField()
    image = models.ImageField(upload_to='products')
    is_active = models.BooleanField(default=False)
    is_bestseller = models.BooleanField(default=False)
    slug = models.SlugField(unique=True, blank=True, null=False, db_index=True, editable=False)
    categories = models.ManyToManyField(Category, blank=True)

    def __str__(self):
        return self.name
    
    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Product, self).save(*args, **kwargs)
        

Account/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User

# Create your views here.

def login_request(request):
    
    if request.user.is_authenticated:
        return redirect('product:home')
    
    if request.method == 'POST':
        username = request.POST.get('username', None)
        password = request.POST.get('password', None)
        
        user = authenticate(request, username=username, password=password)
        
        if user is not None:
            login(request, user)
            return redirect('product:home')
        else:
            return render(request, 'Account/login.html', {'error': 'Invalid username or password'})
        
    return render(request, 'Account/login.html')


def register_request(request):
    
    if request.user.is_authenticated:
        return redirect('product:home')
    
    if request.method == 'POST':
        firstname = request.POST.get('firstname')
        lastname = request.POST.get('lastname')
        username = request.POST.get('username')
        email = request.POST.get('email')
        password = request.POST.get('password')
        repassword = request.POST.get('repassword')
        
        if password == repassword:
            if User.objects.filter(username=username).exists():
                return render(request, 'Account/register.html', {
                    'error': 'Username already exists',
                    'firstname': firstname,
                    'lastname': lastname,
                    'username': username,
                    'email': email
                    })
            else:
                if User.objects.filter(email=email).exists():
                    return render(request, 'Account/register.html', {
                        'error': 'Email already exists',
                        'firstname': firstname,
                        'lastname': lastname,
                        'username': username,
                        'email': email
                        })
                else:
                    user = User.objects.create_user(username=username, email=email, password=password, first_name=firstname, last_name=lastname)
                    user.save()
                    return redirect('account:login')
        else:
            return render(request, 'Account/register.html', {
                'error': 'Passwords do not match',
                'firstname': firstname,
                'lastname': lastname,
                'username': username,
                'email': email
                })
    return render(request, 'Account/register.html')

def logout_request(request):
    logout(request)
    return redirect('product:home')

Product/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Product, Category

# Create your views here.

def index(request):
    context = {
        'products' : Product.objects.filter(is_active=True, is_bestseller=True),
        'categories' : Category.objects.all()
    }
    return render(request, 'Product/index.html', context)

def products(request):
    context = {
        'products' : Product.objects.filter(is_active=True),
        'categories' : Category.objects.all()
    }
    return render(request, 'Product/products.html', context)

def product_detail(request, slug):
    product = Product.objects.get(slug=slug)
    
    return render(request, 'Product/product_detail.html', {
        'product': product
    })

def category_detail(request, slug):
    context = {
        'products' : Category.objects.get(slug=slug).product_set.all().filter(is_active=True),
        'categories' : Category.objects.all(),
        'selected_category' : slug
    }
    return render(request, 'Product/products.html', context)

Product/templates/Product/index.html
{% extends 'base.html' %}

{% load static %}

{% block css %}

    <link rel="stylesheet" href="{% static 'Product/css/style.css' %}">

{% endblock %}

{% block title %}Home{% endblock %}

{% block content %}

    <section>
        <div class="container mt-4">
        <div class="row">
            <div class="col-3">
                {% include 'partials/_categories.html' %}
            </div>
            <div class="col-8">
                <h1>Home Page</h1>
                <hr>
                {% for product in products %}
                    {% if product.is_bestseller and product.is_active %}
                        {% include 'Product/partials/_product.html' %}
                    {% endif %}
                {% endfor %}
            </div>
        </div>
        </div>
    </section>


{% endblock %}

Product/templates/Product/partials/_product.html
{% load static %}
{% load custom_filters %}

<div class="card border border-2 border-black mb-3" style="width: 100%;">
    <div class="row align-items-center px-3">
    <div class="col-md-4">
        <img src="{{ product.image.url }}" class="img-fluid rounded-start m-2" />
    </div>
    <div class="col-md-8">
        <div class="card-body">
            <h5 class="card-title"><a href="{% url 'product:product_detail' product.slug %}">{{ product.name }}</a></h5>
            <p class="card-text">{{ product.description|truncate_html_content:100 }}</p>
        </div>
    </div>
    </div>
</div>

Product/templates/Product/product_detail.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Product Details{% endblock %}

{% block css %}
    <link rel="stylesheet" href="{% static 'Product/css/style.css' %}">
{% endblock %}

{% block content %}


<section>
    <div class="container mt-4">
        <div class="row">
            <div class="col-12">
                    <div class="card border border-2 border-black mb-3" style="width: 100%;">
                        <div class="row align-items-center px-3">
                        <div class="col-md-4">
                            <img src="{{ product.image.url }}" class="img-fluid rounded-start m-2" />
                        </div>
                        <div class="col-md-8">
                            <div class="card-body">
                            <h5 class="card-title">
                                {{ product.name }} - {{ product.price }} $
                            </h5>
                            <p class="card-text">{{ product.description | safe }}</p>
                            </div>
                        </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>


{% endblock %}

{% block js %}
{% endblock %}

Product/templates/Product/products.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Products{% endblock %}

{% block css %}
    <link rel="stylesheet" href="{% static 'Product/css/style.css' %}">
{% endblock %}

{% block content %}


    <section>
        <div class="container mt-4">
            <div class="row">
                <div class="col-3">
                    {% include 'partials/_categories.html' %}
                </div>
                <div class="col-8">
                    <h1>Products Page</h1>
                    <hr>
                    {% if products|length > 0 %}
                    {% for product in products %}
                        {% if product.is_active %}
                            {% include 'Product/partials/_product.html' %}
                        {% endif %}
                    {% endfor %}
                    {% else %}
                        <div class="alert alert-success">No Products Available</div>
                    {% endif %}
                </div>
            </div>
        </div>
    </section>


{% endblock %}

{% block js %}
    <script src="{% static 'Product/js/script.js' %}"></script>
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'css/base.css' %}" />
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />
    {% block css %}

    {% endblock %}
    <title>
      {% block title %}

      {% endblock %}| BlogApp
    </title>
  </head>
  <body>

    {% include 'partials/_navbar.html' %}

    {% block content %} {% endblock %}

    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/base.js' %}"></script>

    {% block js %}

    {% endblock %}
  </body>
</html>

templates/partials/_categories.html
<div class="list-group">
    {% for category in categories %}
        {% if category.slug == selected_category %}
            <a href="{% url 'product:category_detail' category.slug %}" class="list-group-item list-group-item-action active list-group-item-dark">{{ category.name }}</a>    
        {% else %}
            <a href="{% url 'product:category_detail' category.slug %}" class="list-group-item list-group-item-action list-group-item-dark">{{ category.name }}</a>
        {% endif %}
    {% endfor %}
</div>

templates/partials/_navbar.html
<nav class="navbar navbar-dark navbar-expand-lg bg-dark">
  <div class="container">
    <a class="navbar-brand text-light" href="{% url 'product:home' %}">ProductApp</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active text-light" aria-current="page" href="{% url 'product:home' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link text-light" href="{% url 'product:products' %}">Products</a>
        </li>
      </ul>
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        {% if request.user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link text-light" href="{% url 'account:logout' %}">Logout</a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-dark text-bg-info" href="">Welcome {{ user.get_full_name | title }}</a>
            </li>
        {% else %}
            <li class="nav-item">
                <a class="nav-link active text-light" aria-current="page" href="{% url 'account:login' %}">Login</a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-light" href="{% url 'account:register' %}">Register</a>
            </li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>